# Generated by Django 4.1.4 on 2022-12-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComtactMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=202)),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=202)),
            ],
        ),
    ]
